feat(dfu-update): add DfuUpdate Plugin Wrapper
ionic-team/ionic-native pull request #3514
Opened 2020-08-18 14:44 UTC by HansKrywaa

I created this PR as Wrapper for my Plugin [DfuUpdate](https://github.com/HansKrywaa/cordova-plugin-dfu-update) which uses Nordic Semiconductor's Device Firmware Update (DFU) service to update a Bluetooth LE device.

2020-10-16 17:22 UTC, danielsogl requested changes

2020-10-16 17:22 UTC, danielsogl commented on src/@ionic-native/plugins/dfu-update/index.ts
> + * import { DfuUpdate } from '@ionic-native/dfu-update';
Add `/ngx` to the import

2020-10-16 17:31 UTC, EinfachHans commented
@danielsogl done

2020-10-16 21:40 UTC, jrobeson commented
shouldn't this be named in a way that specifics that it's for nordic devices only?

2020-11-19 07:40 UTC, danielsogl approved these changes

2020-11-19 07:40 UTC, merged