feat(background-upload): add plugin
ionic-team/ionic-native pull request #3539
Opened 2020-09-18 07:36 UTC by MaximBelov

2020-10-16 17:18 UTC, danielsogl requested changes

2020-10-16 17:18 UTC, danielsogl commented on src/@ionic-native/plugins/background-upload/index.ts
> + * import { BackgroundUpload } from '@ionic-native/background-upload/npx';
Change it to `/ngx`

2020-11-19 07:39 UTC, MaximBelov commented on src/@ionic-native/plugins/background-upload/index.ts
> + * import { BackgroundUpload } from '@ionic-native/background-upload/npx';
@danielsogl 
done

2020-11-19 07:40 UTC, danielsogl approved these changes

2020-11-19 07:40 UTC, merged