feat(unvired-cordova-sdk): add ability to receive the JWT token
ionic-team/ionic-native pull request #3671
Opened 2021-05-21 06:23 UTC by srinidhirao

2021-06-29 11:44 UTC, danielsogl commented
@srinidhirao please remove the package-lock changes from your PR

2021-06-29 11:44 UTC, danielsogl requested changes
Remove `package-lock.json` from the PR

2021-07-01 08:35 UTC, srinidhirao commented
@danielsogl I have pushed new changes. Can you please check again?

2021-08-02 20:43 UTC, danielsogl approved these changes

2021-08-02 20:43 UTC, merged